version: '3.1'
services:
  client:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client-service
    environment:
      - NATS_URL=nats://natsmq:4222
    ports:
      - 8888:8888
  storage:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    container_name: storage-service
    environment:
      - NATS_URL=nats://natsmq:4222
      - MONGO_DSN=mongodb://mongo:27017