// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/newsclient.proto

package newsclient

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type News struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Header               string               `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *News) Reset()         { *m = News{} }
func (m *News) String() string { return proto.CompactTextString(m) }
func (*News) ProtoMessage()    {}
func (*News) Descriptor() ([]byte, []int) {
	return fileDescriptor_062a10ac6de198ad, []int{0}
}

func (m *News) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_News.Unmarshal(m, b)
}
func (m *News) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_News.Marshal(b, m, deterministic)
}
func (m *News) XXX_Merge(src proto.Message) {
	xxx_messageInfo_News.Merge(m, src)
}
func (m *News) XXX_Size() int {
	return xxx_messageInfo_News.Size(m)
}
func (m *News) XXX_DiscardUnknown() {
	xxx_messageInfo_News.DiscardUnknown(m)
}

var xxx_messageInfo_News proto.InternalMessageInfo

func (m *News) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *News) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *News) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_062a10ac6de198ad, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FindRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_062a10ac6de198ad, []int{2}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindResponse struct {
	News                 *News    `protobuf:"bytes,1,opt,name=news,proto3" json:"news,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_062a10ac6de198ad, []int{3}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetNews() *News {
	if m != nil {
		return m.News
	}
	return nil
}

func (m *FindResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *FindResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*News)(nil), "newsclient.News")
	proto.RegisterType((*CreateResponse)(nil), "newsclient.CreateResponse")
	proto.RegisterType((*FindRequest)(nil), "newsclient.FindRequest")
	proto.RegisterType((*FindResponse)(nil), "newsclient.FindResponse")
}

func init() { proto.RegisterFile("proto/newsclient.proto", fileDescriptor_062a10ac6de198ad) }

var fileDescriptor_062a10ac6de198ad = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xcf, 0x6b, 0xc2, 0x30,
	0x14, 0xc7, 0x69, 0xa7, 0x42, 0x5e, 0x87, 0x8c, 0x30, 0xa4, 0xc8, 0xc6, 0x24, 0xec, 0xe0, 0x29,
	0x05, 0x77, 0xd9, 0x75, 0xc8, 0x06, 0x5e, 0x76, 0x08, 0xfe, 0x03, 0xd5, 0xbc, 0xd9, 0x80, 0x26,
	0x5d, 0x12, 0xf1, 0xdf, 0x1f, 0x7d, 0xd1, 0x75, 0xec, 0xe8, 0xf1, 0xfb, 0x83, 0x7c, 0xf2, 0xbe,
	0x30, 0x69, 0xbd, 0x8b, 0xae, 0xb2, 0x78, 0x0a, 0xdb, 0xbd, 0x41, 0x1b, 0x25, 0x19, 0x1c, 0x7a,
	0x67, 0xfa, 0xb4, 0x73, 0x6e, 0xb7, 0xc7, 0x8a, 0x92, 0xcd, 0xf1, 0xab, 0x8a, 0xe6, 0x80, 0x21,
	0xd6, 0x87, 0x36, 0x95, 0x45, 0x03, 0x83, 0x4f, 0x3c, 0x05, 0x3e, 0x86, 0xdc, 0xe8, 0x32, 0x9b,
	0x65, 0x73, 0xa6, 0x72, 0xa3, 0xf9, 0x04, 0x46, 0x0d, 0xd6, 0x1a, 0x7d, 0x99, 0x93, 0x77, 0x56,
	0xfc, 0x15, 0xd8, 0xd6, 0x63, 0x1d, 0x51, 0xbf, 0xc5, 0xf2, 0x66, 0x96, 0xcd, 0x8b, 0xc5, 0x54,
	0x26, 0x88, 0xbc, 0x40, 0xe4, 0xfa, 0x02, 0x51, 0x7d, 0x59, 0xac, 0x61, 0xbc, 0x24, 0xa1, 0x30,
	0xb4, 0xce, 0x06, 0xec, 0x98, 0xab, 0x5f, 0xe6, 0x4a, 0xf3, 0x07, 0x60, 0xef, 0xde, 0x3b, 0xbf,
	0x74, 0x1a, 0x09, 0x3b, 0x54, 0xbd, 0xc1, 0xef, 0x61, 0x48, 0x82, 0xa8, 0x4c, 0x25, 0x21, 0x1e,
	0xa1, 0xf8, 0x30, 0x56, 0x2b, 0xfc, 0x3e, 0x62, 0x88, 0xff, 0x9f, 0x14, 0x0d, 0xdc, 0xa6, 0xf8,
	0x8c, 0x7c, 0x86, 0x41, 0xb7, 0x0e, 0x35, 0x8a, 0xc5, 0x9d, 0xfc, 0x33, 0x5e, 0x37, 0x83, 0xa2,
	0xf4, 0x9a, 0x8f, 0x6c, 0x46, 0x74, 0xfd, 0xcb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x58,
	0x44, 0xd0, 0x96, 0x01, 0x00, 0x00,
}
